#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "=========================================="
echo "Prediction System Status"
echo "=========================================="
echo ""
echo "Processes:"
ps aux | grep -E "collector|api\.py|predictor_loop|start_all" | grep -v grep | awk '{print "  " $11 " " $12}'
echo ""
echo "BTC  Count: $(python3 -c "import sqlite3; c=sqlite3.connect('$SCRIPT_DIR/prediction/bitcoin/bitcoin_prices.db').cursor(); c.execute('SELECT COUNT(*) FROM prices'); print(c.fetchone()[0])" 2>/dev/null || echo 'N/A')"
echo "BNB  Count: $(python3 -c "import sqlite3; c=sqlite3.connect('$SCRIPT_DIR/prediction/bnb/bnb_prices.db').cursor(); c.execute('SELECT COUNT(*) FROM prices'); print(c.fetchone()[0])" 2>/dev/null || echo 'N/A')"
echo "HYPE Count: $(python3 -c "import sqlite3; c=sqlite3.connect('$SCRIPT_DIR/prediction/hype/hype_prices.db').cursor(); c.execute('SELECT COUNT(*) FROM prices'); print(c.fetchone()[0])" 2>/dev/null || echo 'N/A')"
echo ""
echo "Unified API: $(curl -s http://localhost:5000/health | python3 -c "import sys,json; print(json.load(sys.stdin).get('status', 'offline'))" 2>/dev/null || echo 'offline')"
echo "BTC API:     $(curl -s http://localhost:5001/health | python3 -c "import sys,json; print(json.load(sys.stdin).get('status', 'offline'))" 2>/dev/null || echo 'offline')"
echo "BNB API:     $(curl -s http://localhost:5002/health | python3 -c "import sys,json; print(json.load(sys.stdin).get('status', 'offline'))" 2>/dev/null || echo 'offline')"
echo ""
echo "Dashboards:"
echo "  Unified: http://localhost:5000"
echo "  BTC:     http://localhost:5001"
echo "  BNB:     http://localhost:5002"
